
# JWT??
jwt:
  secret: MySecretKey123  # ?????JWT??
  expiration: 1800000         # ?????????????????????????????

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 123456

