
server:
  tomcat:
    threads:
      max: 800

jwt:
  secret: MySecretKey123
  expiration: 1800000

spring:
  datasource:
    url: jdbc:mysql://192.168.194.135:3306/mydb
    username: root
    password: 991103Lxy..


  redis:
    database: 1
    host: 192.168.194.135
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 5
        max-wait: 5000

#jasypt:
#  encryptor:
#    password: 123456

