
server:
  tomcat:
    threads:
      max: 800

jwt:
  secret: MySecretKey123
  expiration: 1800000

spring:
  datasource:
    url: jdbc:mysql://192.168.194.133:3306/mydb
    username: root
    password: 991103Lxy..

#jasypt:
#  encryptor:
#    password: 123456

